# Generated by Django 6.0 on 2025-12-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('os_type', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('owner', models.CharField(max_length=100)),
                ('compliance_status', models.BooleanField(default=False)),
            ],
        ),
    ]
